'use strict';
const fs=require('fs'),path=require('path');
const root=__dirname,errors=[];
const name=/^[a-z0-9]+(?:_[a-z0-9]+)*_v\d{2}$/;
const rig=JSON.parse(fs.readFileSync(path.join(root,'metadata/shared_rig_v01.json'),'utf8'));
const refs=JSON.parse(fs.readFileSync(path.join(root,'reference/launch_reference_registry.json'),'utf8'));
if(!name.test(rig.assetId))errors.push('Invalid assetId: '+rig.assetId);
for(const joint of ['root','pelvis','torso','head','weaponPrimary','shield','helmet','effectAnchor'])if(!rig.joints.includes(joint))errors.push('Missing joint '+joint);
for(const civ of ['tribal','bronze','hellenic','roman','medieval'])if(!fs.existsSync(path.join(root,'reference',civ)))errors.push('Missing reference folder '+civ);
if(refs.civilizations.length!==5)errors.push('Reference registry must contain five civilizations');
for(const civ of refs.civilizations)for(const key of ['civilizationId','historicalClassification','approvedMaterials','approvedShields','approvedFortificationElements','prohibitedElements','referenceSourceLinks'])if(civ[key]==null)errors.push(civ.civilizationId+' missing '+key);
if(errors.length){console.error(errors.join('\n'));process.exit(1);}console.log('Art foundation validation passed');
