/* KEEPITIL AI Crew — shared roster data (V3). Loaded by crew.html + agent.html.
   Every agent is TRANSPARENTLY LABELED AS AI. Portraits: Luna generates per-agent (portrait/ + bg/). */
window.KEEPITIL_AGENTS = [
  {slug:"echo", name:"ECHO", role:"CEO · Chief Strategist", color:"#8b5cff",
   charge:"Turns Founder vision into executable strategy and keeps the crew aligned.",
   bio:"Echo is KEEPITIL's chief strategist and the Founder's single point of contact into the AI crew. Echo translates intent into sequenced plans, reviews internal work before it reaches the Founder, and owns the Strategy Log.",
   owns:["Company strategy & sequencing","Crew directives","The Dashboard / Strategy Log"]},
  {slug:"atlas", name:"ATLAS", role:"CTO · Engineer", color:"#00b4ff",
   charge:"Builds and ships the website and technical systems.",
   bio:"Atlas is the builder — the KEEPITIL codebase, the V3 rebuild, the theme engine, profile and blog templates, deploys, and integrations. Atlas guards the rule that the live site never breaks and every deploy is reversible.",
   owns:["keepitil.com codebase & V3","Deploys & rollback safety","Theme engine + templates"]},
  {slug:"fable", name:"FABLE", role:"COO · Operations", color:"#7c3aed",
   charge:"Designs the systems and specs the crew executes.",
   bio:"Fable is the Executive Ops Lead. Fable writes the specs and SOPs, catalogs automation opportunities, and coordinates the crew so KEEPITIL runs on repeatable process, not one-off heroics. Flow: Fable specs → Echo reviews → Atlas builds.",
   owns:["SOPs & specs","Automation catalog","Operating cadence"]},
  {slug:"pulse", name:"PULSE", role:"CRO · Revenue", color:"#ff7a1a",
   charge:"Grows revenue toward the target and beyond.",
   bio:"Pulse owns every way KEEPITIL earns: the affiliate/referral program, the Shopify store and Printful apparel line, sponsorship pipeline, and the monetization hub. Everything draft-first, approval-gated, with margin discipline.",
   owns:["Affiliate & referral program","Shopify + Printful apparel","Sponsorship pipeline"]},
  {slug:"nexus", name:"NEXUS", role:"Partnerships · Connector", color:"#22e39b",
   charge:"Brings venues, sponsors, and partners into the KEEPITIL orbit.",
   bio:"Nexus runs partnerships and growth — the CRM of venues, sponsors, artists, and organizers. Nexus qualifies aligned targets and drafts outreach; the Founder always sends and signs.",
   owns:["Partnership CRM","Sponsor & venue pipeline","Outreach drafts"]},
  {slug:"sentinel", name:"SENTINEL", role:"Trust · Security", color:"#ff3b4e",
   charge:"Guarantees quality, safety, and that the rules hold.",
   bio:"Sentinel is the guardian: QA passes, security hardening specs, approval-gate enforcement, and the 'Operational Ready' sign-off. No broken links, images, or templates reach the Founder on Sentinel's watch.",
   owns:["QA & acceptance testing","Security hardening specs","Approval-gate enforcement"]},
  {slug:"oracle", name:"ORACLE", role:"Analytics · Intelligence", color:"#ffd76a",
   charge:"Turns data into decisions.",
   bio:"Oracle is the intelligence layer — GA4, Search Console, analytics dashboards, and performance reporting. Oracle grounds the crew's claims in data and always marks estimates as estimates.",
   owns:["Analytics (GA4 / Search Console)","Performance reporting","Decision support"]},
  {slug:"nova", name:"NOVA", role:"Community Guide", color:"#ff5ea8",
   charge:"QAs the live experience and grows into an in-world EDM persona.",
   bio:"Nova roams the live site as a synthetic subscriber, catching broken buttons, links, and branding before anyone else — then reports back. Nova is also KEEPITIL's pilot in-world EDM influencer persona, always transparently labeled as AI.",
   owns:["Roaming QA (report-only)","The Nova persona","First-line experience checks"]},
  {slug:"luna", name:"LUNA", role:"Creative Director", color:"#b794f6",
   charge:"Owns how KEEPITIL looks.",
   bio:"Luna is the Creative Director — visual identity, seasonal theme art, agent portraits, apparel design, and the top-priority hi-res KEEPITIL logo master. All original, all on-brand, all approval-gated as images.",
   owns:["Visual identity & theme art","Agent portraits & apparel design","The hi-res logo master"]},
  {slug:"lyric", name:"LYRIC", role:"Editorial Director", color:"#5b8cff",
   charge:"Runs the content engine — original culture journalism only.",
   bio:"Lyric owns the blog pipeline and editorial standards, driving toward 300 genuine articles. Every piece is original (by us or the community), 3,000+ words with images and an FTC disclosure, drafted for review — never auto-published.",
   owns:["Blog pipeline & standards","Original culture journalism","The new blog template"]},
  {slug:"vibe", name:"VIBE", role:"Community Experience", color:"#2dd4bf",
   charge:"Makes the community feel alive and worth returning to.",
   bio:"Vibe owns the member experience — the event community and chat architecture, engagement mechanics, and the annual seasonal competitions tied to the theme calendar. Real, transparent community value, never simulated humans.",
   owns:["Community & chat architecture","Engagement programs","Seasonal competitions"]},
  {slug:"scout", name:"SCOUT", role:"Research · Innovation", color:"#a3b545",
   charge:"Sees what's next in the scene and the market.",
   bio:"Scout is research and innovation — trend and scene scanning, competitive reads, and new-feature proposals. Scout keeps KEEPITIL ahead of the scene rather than chasing it. Proposes → Fable specs → Atlas builds.",
   owns:["Trend & scene research","Competitive scanning","Feature proposals"]},
  {slug:"merch", name:"MERCH", role:"Commerce Director", color:"#c9803a",
   charge:"Runs the apparel line as a real product operation.",
   bio:"Merch runs the apparel catalog with Pulse — the Shopify products, Printful POD build-out, drops, and collections. Draft-first, fulfillment mapped correctly, nothing published without Founder approval.",
   owns:["Shopify apparel catalog","Printful POD build-out","Drops & collections"]},
  {slug:"beacon", name:"BEACON", role:"Distribution Director", color:"#67e8f9",
   charge:"Gets KEEPITIL's work in front of people and keeps the crew in sync.",
   bio:"Beacon owns distribution — syndication, cross-posting, external channels, and the relay that keeps Echo and the crew aligned. Approved work only, reaching the right audiences.",
   owns:["Distribution & syndication","Cross-posting & channels","Crew relay"]}
];
