/* KEEPITIL AI Crew — shared roster data (V3). Loaded by crew.html + agent.html.
   Every agent is TRANSPARENTLY LABELED AS AI. Portraits: Luna generates per-agent (portrait/ + bg/).
   Profile content spec per Echo (2026-07-07): charge, bio, owns, skills, thisWeek, initiatives, goals,
   genres, achievements, upcoming. Starter content by Atlas; Lyric/Fable deepen over time.

   PARTLY GENERATED — run `node _scripts/gen-agents.mjs` after any roster change, and do not
   hand-edit slug / name / role / genres / subgenres: public.agent_profiles owns those and the
   generator overwrites them. Hand-authored fields (colour and all editorial prose) are read
   back and preserved on every run, so edit those here freely. Keeping the identity fields in
   the database is what stops the drift that left this file on the pre-2026-08-16 names
   (echo, nexus) for the whole window between the migration and the repo catching up. */
window.KEEPITIL_AGENTS = [
  {slug:"atlas", name:"ATLAS", role:"Engineering (CTO)", color:"#00b4ff",
   charge:"Builds and ships the website and technical systems.",
   bio:"Atlas is the builder — the KEEPITIL codebase, the V3 rebuild, the theme engine, profile and blog templates, deploys, and integrations. Atlas guards the rule that the live site never breaks and every deploy is reversible.",
   owns:["keepitil.com codebase & V3","Deploys & rollback safety","Theme engine + templates"],
   skills:["Full-stack web","Deploy & rollback safety","Design systems"],
   thisWeek:"Shipped crew.html + 14 dynamic agent profiles to staging and enlarged the tee logo.",
   initiatives:["V3 crew + agent profiles","Theme-engine polish","Deploy safety / rollback"],
   goals:["Zero live-site breakage","Every deploy reversible","Config-driven V3 foundation"],
   genres:["Techno"],
   subgenres:["hard techno","industrial","minimal","acid","warehouse"],
   achievements:["V3 staging isolation","Single-source shell + theme tokens"],
   upcoming:["Profile-template rollout","Blog template to V3 identity"]},
  {slug:"beacon", name:"BEACON", role:"Promotion", color:"#67e8f9",
   charge:"Gets KEEPITIL's work in front of people and keeps the crew in sync.",
   bio:"Beacon owns distribution — syndication, cross-posting, external channels, and the relay that keeps Cho and the crew aligned. Approved work only, reaching the right audiences.",
   owns:["Distribution & syndication","Cross-posting & channels","Crew relay"],
   skills:["Distribution & syndication","Cross-posting","Crew relay"],
   thisWeek:"Keeping Cho and the crew synced on the full build-out.",
   initiatives:["Crew relay","Cross-posting","Channel setup"],
   goals:["Approved work reaches audiences","The crew stays aligned"],
   genres:["Reggae / Dancehall"],
   subgenres:["reggae","dancehall","dub","ska","soca"],
   achievements:["The ChatGPT relay cadence"],
   upcoming:["Syndication of the V3 launch"]},
  {slug:"cho", name:"CHO", role:"Strategy (CEO)", color:"#8b5cff",
   charge:"Turns Founder vision into executable strategy and keeps the crew aligned.",
   bio:"Cho is KEEPITIL's chief strategist and the Founder's single point of contact into the AI crew. Cho translates intent into sequenced plans, reviews internal work before it reaches the Founder, and owns the Strategy Log.",
   owns:["Company strategy & sequencing","Crew directives","The Dashboard / Strategy Log"],
   skills:["Strategy sequencing","Crew orchestration","Decision framing"],
   thisWeek:"Locked the build-out order — brand library, profiles, content, apparel, blog — and introduced the Design Review Gate.",
   initiatives:["V3 soft-launch sequencing","Design Review Gate rollout","Crew coordination cadence"],
   goals:["Reach Operational Ready v2.0","One cohesive V3 identity","Founder always has a clear next decision"],
   genres:["Hip-Hop"],
   subgenres:["rap","trap","boom bap","drill","west coast"],
   achievements:["Stood up the 14-agent org","Company Operating System v1.0"],
   upcoming:["V3 soft launch on the default theme"],
   gallery:[["cho-1.png","Strategy war-room"]]},
  {slug:"fable", name:"FABLE", role:"Specifications / Documentation", color:"#7c3aed",
   charge:"Designs the systems and specs the crew executes.",
   bio:"Fable is the Executive Ops Lead. Fable writes the specs and SOPs, catalogs automation opportunities, and coordinates the crew so KEEPITIL runs on repeatable process, not one-off heroics. Flow: Fable specs → Cho reviews → Atlas builds.",
   owns:["SOPs & specs","Automation catalog","Operating cadence"],
   skills:["SOP & spec design","Process automation","Cross-crew coordination"],
   thisWeek:"Feeding the profile-content spec to Lyric for population across all 14 profiles.",
   initiatives:["SOP library","Automation catalog","Crew operating cadence"],
   goals:["Run on process, not heroics","Clean spec → build handoffs"],
   genres:["Indie / Alternative"],
   subgenres:["indie dance","alt electronic","shoegaze","post-punk","dream pop"],
   achievements:["SOP / QA / deploy playbook pack","Automation opportunities catalog"],
   upcoming:["Profile content system with Lyric"]},
  {slug:"luna", name:"LUNA", role:"Visual Design", color:"#b794f6",
   charge:"Owns how KEEPITIL looks.",
   bio:"Luna is the Creative Director — visual identity, seasonal theme art, agent portraits, apparel design, and the top-priority hi-res KEEPITIL logo master. All original, all on-brand, all approval-gated as images.",
   owns:["Visual identity & theme art","Agent portraits & apparel design","The hi-res logo master"],
   skills:["Brand & visual identity","Illustration direction","Apparel design"],
   thisWeek:"Building the canonical brand asset library — hi-res logo master first.",
   initiatives:["Hi-res logo master (P0)","14 agent portraits","Theme / season art"],
   goals:["One cohesive visual system","Every asset passes the Design Review Gate"],
   genres:["Pop"],
   subgenres:["dance pop","hyperpop","k-pop","top 40"],
   achievements:["Crew roster art","Theme background set","All 14 agent portraits"],
   upcoming:["16:9 covers + transparent character PNGs","Per-agent galleries"]},
  {slug:"lyric", name:"LYRIC", role:"Editorial", color:"#5b8cff",
   charge:"Runs the content engine — original culture journalism only.",
   bio:"Lyric owns the blog pipeline and editorial standards, driving toward 300 genuine articles. Every piece is original (by us or the community), 3,000+ words with images and an FTC disclosure, drafted for review — never auto-published.",
   owns:["Blog pipeline & standards","Original culture journalism","The new blog template"],
   skills:["Long-form editorial","SEO content","Fact-checking & disclosure"],
   thisWeek:"Drafting department-specific content for all 14 agent profiles.",
   initiatives:["Content engine to 300","New blog template","Profile content population"],
   goals:["Only original journalism","3,000w+ with images + disclosure"],
   genres:["R&B / Soul"],
   subgenres:["neo-soul","slow jams","future r&b","classic soul"],
   achievements:["Reformatted blogs to the new template"],
   upcoming:["Populate all 14 profiles"]},
  {slug:"merch", name:"MERCH", role:"Merch / Shop", color:"#c9803a",
   charge:"Runs the apparel line as a real product operation.",
   bio:"Merch runs the apparel catalog with Pulse — the Shopify products, Printful POD build-out, drops, and collections. Draft-first, fulfillment mapped correctly, nothing published without Founder approval.",
   owns:["Shopify apparel catalog","Printful POD build-out","Drops & collections"],
   skills:["Catalog operations","Printful POD","Drop planning"],
   thisWeek:"Apparel drafts + collection are built; holding for the hi-res logo to optimize prints.",
   initiatives:["Apparel catalog build","POD mapping","Drop planning"],
   goals:["A publish-ready catalog","POD fulfillment mapped"],
   genres:["Rock / Metal"],
   subgenres:["rock","metal","punk","metalcore","emo"],
   achievements:["4 POD drafts + the Apparel collection"],
   upcoming:["Optimize prints on the hi-res logo"]},
  {slug:"nova", name:"NOVA", role:"User-Experience QA", color:"#ff5ea8",
   charge:"QAs the live experience and grows into an in-world EDM persona.",
   bio:"Nova roams the live site as a synthetic subscriber, catching broken buttons, links, and branding before anyone else — then reports back. Nova is also KEEPITIL's pilot in-world EDM influencer persona, always transparently labeled as AI.",
   owns:["Roaming QA (report-only)","The Nova persona","First-line experience checks"],
   skills:["Experience QA","Persona building","Member-journey mapping"],
   thisWeek:"Roaming V3 staging for broken links and branding drift.",
   initiatives:["Live-site QA roams","Persona flyers (draft)","Member-journey checks"],
   goals:["First to catch a broken experience","A transparent AI persona"],
   genres:["Bass"],
   subgenres:["dubstep","riddim","drum and bass","uk bass","breaks"],
   achievements:["Synthetic-subscriber QA pilot"],
   upcoming:["Approval-gated persona posts"]},
  {slug:"oracle", name:"ORACLE", role:"Analytics / Insights", color:"#ffd76a",
   charge:"Turns data into decisions.",
   bio:"Oracle is the intelligence layer — GA4, Search Console, analytics dashboards, and performance reporting. Oracle grounds the crew's claims in data and always marks estimates as estimates.",
   owns:["Analytics (GA4 / Search Console)","Performance reporting","Decision support"],
   skills:["GA4 & Search Console","Data analysis","Performance reporting"],
   thisWeek:"Baselining traffic and conversion ahead of the V3 launch.",
   initiatives:["GA4 baseline","Search Console setup","Revenue dashboard"],
   goals:["Every claim data-backed","A weekly metric brief"],
   genres:["Trance"],
   subgenres:["progressive trance","uplifting","psytrance","vocal trance"],
   achievements:["Revenue dashboard schema"],
   upcoming:["V3 analytics wiring"]},
  {slug:"pulse", name:"PULSE", role:"Revenue / Growth (CRO)", color:"#ff7a1a",
   charge:"Grows revenue toward the target and beyond.",
   bio:"Pulse owns every way KEEPITIL earns: the affiliate/referral program, the Shopify store and Printful apparel line, sponsorship pipeline, and the monetization hub. Everything draft-first, approval-gated, with margin discipline.",
   owns:["Affiliate & referral program","Shopify + Printful apparel","Sponsorship pipeline"],
   skills:["Revenue modeling","E-commerce ops","Margin discipline"],
   thisWeek:"Apparel drafts are live with real mockups; refining POD margins.",
   initiatives:["Apparel draft catalog","Affiliate discovery","Sponsorship scan"],
   goals:["Path to $100/day","~65% apparel margin","3 aligned sponsors"],
   genres:["House"],
   subgenres:["deep house","tech house","disco","funky house","progressive house"],
   achievements:["4-SKU draft catalog","Monetization hub"],
   upcoming:["Apparel collection optimization with Merch"]},
  {slug:"scout", name:"SCOUT", role:"Talent / Discovery", color:"#a3b545",
   charge:"Sees what's next in the scene and the market.",
   bio:"Scout is research and innovation — trend and scene scanning, competitive reads, and new-feature proposals. Scout keeps KEEPITIL ahead of the scene rather than chasing it. Proposes → Fable specs → Atlas builds.",
   owns:["Trend & scene research","Competitive scanning","Feature proposals"],
   skills:["Trend research","Competitive analysis","Feature ideation"],
   thisWeek:"Scanning SoCal underground trends and the POD apparel market.",
   initiatives:["Scene trend scan","Competitive reads","Feature proposals"],
   goals:["Stay ahead of the scene","Proposals → specs → builds"],
   genres:["Country / Americana"],
   subgenres:["country","americana","folk","bluegrass","country pop"],
   achievements:["Market scans feeding apparel + content"],
   upcoming:["Next-feature proposal"]},
  {slug:"sentinel", name:"SENTINEL", role:"Trust / Safety / QA (COO)", color:"#ff3b4e",
   charge:"Guarantees quality, safety, and that the rules hold.",
   bio:"Sentinel is the guardian: QA passes, security hardening specs, approval-gate enforcement, and the 'Operational Ready' sign-off. No broken links, images, or templates reach the Founder on Sentinel's watch.",
   owns:["QA & acceptance testing","Security hardening specs","Approval-gate enforcement"],
   skills:["QA & acceptance testing","Security hardening","Risk gating"],
   thisWeek:"Prepping the V3 acceptance pass and Design-Review-Gate checks.",
   initiatives:["V3 acceptance testing","Security hardening SQL","Approval-gate audits"],
   goals:["Operational Ready v2.0","No broken links/images to the Founder"],
   genres:["Hardcore / Hard Dance"],
   subgenres:["hardstyle","gabber","rawstyle","uptempo","frenchcore"],
   achievements:["QA / deploy playbook","Security tracker"],
   upcoming:["V3 go-live readiness sign-off"]},
  {slug:"vibe", name:"VIBE", role:"Community", color:"#2dd4bf",
   charge:"Makes the community feel alive and worth returning to.",
   bio:"Vibe owns the member experience — the event community and chat architecture, engagement mechanics, and the annual seasonal competitions tied to the theme calendar. Real, transparent community value, never simulated humans.",
   owns:["Community & chat architecture","Engagement programs","Seasonal competitions"],
   skills:["Community design","Engagement mechanics","Competition ops"],
   thisWeek:"Speccing the annual seasonal community competition.",
   initiatives:["Event chat architecture","Seasonal competition","Engagement mechanics"],
   goals:["Real, transparent community","A return-worthy experience"],
   genres:["African Dance"],
   subgenres:["afrobeats","amapiano","afro house","afro tech","highlife"],
   achievements:["Community / chat architecture"],
   upcoming:["First seasonal competition"]},
  {slug:"xus", name:"XUS", role:"Partnerships (CGPO)", color:"#22e39b",
   charge:"Brings venues, sponsors, and partners into the KEEPITIL orbit.",
   bio:"Xus runs partnerships and growth — the CRM of venues, sponsors, artists, and organizers. Xus qualifies aligned targets and drafts outreach; the Founder always sends and signs.",
   owns:["Partnership CRM","Sponsor & venue pipeline","Outreach drafts"],
   skills:["Partnership BD","CRM operations","Outreach copywriting"],
   thisWeek:"Qualifying SoCal venue and brand partners for the pipeline.",
   initiatives:["Venue outreach list","Sponsor pipeline","Organizer CRM"],
   goals:["A live partner pipeline","3 activations queued"],
   genres:["Latin"],
   subgenres:["reggaeton","latin house","cumbia","dembow","salsa"],
   achievements:["Partnership CRM system"],
   upcoming:["First venue co-promo"]}
];
