(function(){
  'use strict';
  const defs={
    military:{label:'Military Research',base:220,desc:'+4% player unit damage per level'},
    engineering:{label:'Engineering Research',base:200,desc:'+5% fortress weapon damage per level'},
    logistics:{label:'Field Logistics',base:180,desc:'+4% shield and armor durability per level'}
  };
  function ensure(){if(!S)return null;S.warCouncil=S.warCouncil||{research:{military:0,engineering:0,logistics:0},repairsThisWave:0,powerChargesThisWave:0,elitePurchases:0,fortOverdriveT:0};if('economy'in S.warCouncil.research){S.warCouncil.research.logistics=S.warCouncil.research.logistics||S.warCouncil.research.economy;delete S.warCouncil.research.economy;}return S.warCouncil;}
  const cost=(key,lvl)=>Math.round(defs[key].base*Math.pow(lvl+1,2)*(1+(S.civ-1)*.12));
  function buyResearch(key){const w=ensure(),lvl=w.research[key]||0;if(lvl>=5)return showMsg('Research is maxed');const price=cost(key,lvl);if(S.gold<price)return showMsg('Not enough gold');S.gold-=price;w.research[key]=lvl+1;if(key==='military')for(const u of S.units)if(u.team===1)u.dmg=Math.round(u.dmg*1.04);showMsg(defs[key].label+' level '+(lvl+1));window.KWAnalytics?.track('war_council_purchase',{type:'research',key,level:lvl+1,cost:price,wave:S.wave});}
  function repair(){const w=ensure(),price=Math.round(100*(1+(S.civ-1)*.12)*(1+w.repairsThisWave*.35)),amount=Math.round(150*(1+(S.civ-1)*.08));if(S.gateHP>=S.gateMax)return showMsg('Fortress is already fully repaired');if(S.gold<price)return showMsg('Not enough gold');S.gold-=price;S.gateHP=Math.min(S.gateMax,S.gateHP+amount);w.repairsThisWave++;showMsg('Fortress repaired +'+amount);}
  function elite(){const w=ensure(),active=S.units.filter(u=>u.team===1&&u.type==='spartan'&&u.hp>0).length,price=Math.round(240*(1+(S.civ-1)*.14)*(1+active*.30));if(armyCount()>=armyMax())return showMsg('Army is full');if(S.gold<price)return showMsg('Not enough gold');S.gold-=price;if(spawnSpartan('war-council-'+(++w.elitePurchases)))showMsg('Elite contract deployed');}
  function charge(){const w=ensure();if(w.powerChargesThisWave>=2)return showMsg('Power acceleration limit reached');if(S.atkCd<=0)return showMsg('Battlefield power is ready');const price=Math.round((w.powerChargesThisWave?300:150)*(1+(S.civ-1)*.1));if(S.gold<price)return showMsg('Not enough gold');S.gold-=price;S.atkCd*=.75;w.powerChargesThisWave++;showMsg('Power cooldown advanced 25%');}
  function overdrive(){const w=ensure(),price=Math.round(350*(1+(S.civ-1)*.15));if(w.fortOverdriveT>0)return showMsg('Fortress Overdrive is active');if(S.gold<price)return showMsg('Not enough gold');S.gold-=price;w.fortOverdriveT=10;showMsg('Fortress Overdrive active for 10 seconds');}
  function render(showPanel){if(!started||!S)return showPanel('WAR COUNCIL','<p class="note">Begin or continue an Endless War to use the War Council.</p>');const w=ensure();const rows=Object.keys(defs).map(k=>{const lvl=w.research[k]||0,p=lvl<5?cost(k,lvl):0;return '<div class="councilrow"><span><b>'+defs[k].label+'</b><small>Level '+lvl+'/5 · '+defs[k].desc+'</small></span><button data-research="'+k+'">'+(lvl>=5?'MAX':'🪙 '+p)+'</button></div>';}).join('');const repairPrice=Math.round(100*(1+(S.civ-1)*.12)*(1+w.repairsThisWave*.35)),active=S.units.filter(u=>u.team===1&&u.type==='spartan'&&u.hp>0).length,elitePrice=Math.round(240*(1+(S.civ-1)*.14)*(1+active*.30)),chargePrice=Math.round((w.powerChargesThisWave?300:150)*(1+(S.civ-1)*.1)),overdrivePrice=Math.round(350*(1+(S.civ-1)*.15));showPanel('WAR COUNCIL · 🪙 '+Math.floor(S.gold),'<button class="menubtn primary" id="wcReturn">RETURN TO BATTLE</button>'+rows+'<hr><div class="councilrow"><span><b>Emergency Repairs</b><small>Restore fortress health. Cost rises each use this wave.</small></span><button id="wcRepair">🪙 '+repairPrice+'</button></div><div class="councilrow"><span><b>Elite Contract</b><small>Deploy one civilization elite. Cost scales with active elites.</small></span><button id="wcElite">🪙 '+elitePrice+'</button></div><div class="councilrow"><span><b>Power Acceleration</b><small>Advance battlefield-power cooldown by 25%. '+w.powerChargesThisWave+'/2 used.</small></span><button id="wcCharge">🪙 '+chargePrice+'</button></div><div class="councilrow"><span><b>Fortress Overdrive</b><small>Double fortress firing speed for 10 seconds.</small></span><button id="wcOverdrive">🪙 '+overdrivePrice+'</button></div>');document.getElementById('wcReturn').onclick=()=>{document.getElementById('hub').classList.add('hidden');document.getElementById('hubpanel').classList.add('hidden');paused=false;document.getElementById('pausebtn').textContent='⏸';};document.querySelectorAll('[data-research]').forEach(b=>b.onclick=()=>{buyResearch(b.dataset.research);render(showPanel);});document.getElementById('wcRepair').onclick=()=>{repair();render(showPanel);};document.getElementById('wcElite').onclick=()=>{elite();render(showPanel);};document.getElementById('wcCharge').onclick=()=>{charge();render(showPanel);};document.getElementById('wcOverdrive').onclick=()=>{overdrive();render(showPanel);};}
  function damageMultiplier(){return 1+(ensure()?.research.military||0)*.04;}
  function fortressMultiplier(){return (1+(ensure()?.research.engineering||0)*.05)*((ensure()?.fortOverdriveT||0)>0?1.25:1);}
  function protectionMultiplier(){return 1+(ensure()?.research.logistics||0)*.04;}
  function tick(dt){const w=ensure();if(w)w.fortOverdriveT=Math.max(0,w.fortOverdriveT-dt);}
  function waveReset(){const w=ensure();if(w){w.repairsThisWave=0;w.powerChargesThisWave=0;}}
  window.KWWarCouncil=Object.freeze({render,ensure,buyResearch,repair,elite,charge,overdrive,damageMultiplier,fortressMultiplier,protectionMultiplier,tick,waveReset});
})();
